"""- author

Revision ID: 08fd5bbe7474
Revises: 93ed8f7fb126
Create Date: 2025-08-11 00:56:40.638274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08fd5bbe7474'
down_revision: Union[str, Sequence[str], None] = '93ed8f7fb126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    op.drop_column('mangas', 'artist')
    op.drop_column('mangas', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mangas', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mangas', sa.Column('artist', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_table('pages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chapter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], name=op.f('pages_manga_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pages_pkey'))
    )
    # ### end Alembic commands ###
