"""catalog 5.0

Revision ID: 275c64418f52
Revises: e5e1645f7b1e
Create Date: 2025-08-25 02:43:20.391346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '275c64418f52'
down_revision: Union[str, Sequence[str], None] = 'e5e1645f7b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mangas1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mangas1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('picture', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alternative_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('chapter_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('volume_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('time', sa.VARCHAR(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('author', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('izdat', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating_10', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_9', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_8', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_7', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_6', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_5', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_4', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_3', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('mangas1_pkey'))
    )
    # ### end Alembic commands ###
