"""new dbs

Revision ID: 4b89a5e11e0e
Revises: cebfdee39dc7
Create Date: 2025-08-11 22:52:15.696428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b89a5e11e0e'
down_revision: Union[str, Sequence[str], None] = 'cebfdee39dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mangas', sa.Column('total_list', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('reading', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('planned', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('completed', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('favorite', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('on_hold', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('dropped', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('total_rating', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('rating_10', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('rating_9', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('rating_8', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('rating_7', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('rating_6', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('rating_5', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('rating_4', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('rating_3', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('rating_2', sa.Integer(), nullable=True))
    op.add_column('mangas', sa.Column('rating_1', sa.Integer(), nullable=True))
    op.drop_column('reviews', 'comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('comments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('mangas', 'rating_1')
    op.drop_column('mangas', 'rating_2')
    op.drop_column('mangas', 'rating_3')
    op.drop_column('mangas', 'rating_4')
    op.drop_column('mangas', 'rating_5')
    op.drop_column('mangas', 'rating_6')
    op.drop_column('mangas', 'rating_7')
    op.drop_column('mangas', 'rating_8')
    op.drop_column('mangas', 'rating_9')
    op.drop_column('mangas', 'rating_10')
    op.drop_column('mangas', 'total_rating')
    op.drop_column('mangas', 'dropped')
    op.drop_column('mangas', 'on_hold')
    op.drop_column('mangas', 'favorite')
    op.drop_column('mangas', 'completed')
    op.drop_column('mangas', 'planned')
    op.drop_column('mangas', 'reading')
    op.drop_column('mangas', 'total_list')
    op.drop_table('comments')
    # ### end Alembic commands ###
