"""comments reviews

Revision ID: 75f1bcd73941
Revises: 275c64418f52
Create Date: 2025-08-26 14:39:38.038634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f1bcd73941'
down_revision: Union[str, Sequence[str], None] = '275c64418f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('comments_review_id_fkey'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'review_id')
    op.drop_column('comments', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('comments_review_id_fkey'), 'comments', 'reviews', ['review_id'], ['id'])
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
