"""int pic

Revision ID: 93ed8f7fb126
Revises: b40373ba268f
Create Date: 2025-08-08 18:24:54.666036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ed8f7fb126'
down_revision: Union[str, Sequence[str], None] = 'b40373ba268f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mangas', 'preview_picture_id',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mangas', 'preview_picture_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
