"""new db 4.0

Revision ID: 98f261ecc5dd
Revises: ef3156d69c04
Create Date: 2025-08-20 14:42:50.752316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f261ecc5dd'
down_revision: Union[str, Sequence[str], None] = 'ef3156d69c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('total_list', sa.Integer(), nullable=False),
    sa.Column('reading', sa.Integer(), nullable=False),
    sa.Column('planned', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('favorite', sa.Integer(), nullable=False),
    sa.Column('on_hold', sa.Integer(), nullable=False),
    sa.Column('dropped', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('total_list', sa.Integer(), nullable=False),
    sa.Column('reading', sa.Integer(), nullable=False),
    sa.Column('planned', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('favorite', sa.Integer(), nullable=False),
    sa.Column('on_hold', sa.Integer(), nullable=False),
    sa.Column('dropped', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('mangas', 'preview_picture_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mangas', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('mangas', 'planned')
    op.drop_column('mangas', 'rating_6')
    op.drop_column('mangas', 'rating_3')
    op.drop_column('mangas', 'rating_5')
    op.drop_column('mangas', 'dropped')
    op.drop_column('mangas', 'on_hold')
    op.drop_column('mangas', 'favorite')
    op.drop_column('mangas', 'rating')
    op.drop_column('mangas', 'rating_4')
    op.drop_column('mangas', 'rating_2')
    op.drop_column('mangas', 'rating_10')
    op.drop_column('mangas', 'completed')
    op.drop_column('mangas', 'reading')
    op.drop_column('mangas', 'rating_8')
    op.drop_column('mangas', 'rating_7')
    op.drop_column('mangas', 'rating_1')
    op.drop_column('mangas', 'total_rating')
    op.drop_column('mangas', 'rating_9')
    op.drop_column('mangas', 'total_list')
    op.alter_column('reviews', 'user',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'reviews', 'users', ['user'], ['id'])
    op.create_foreign_key(None, 'reviews', 'mangas', ['manga_id'], ['id'])
    op.add_column('users', sa.Column('login', sa.String(), nullable=False))
    op.alter_column('users', 'bookmarks',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.Integer()),
               existing_nullable=False)
    op.create_foreign_key(None, 'users', 'mangas', ['bookmarks'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'bookmarks',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'login')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.alter_column('reviews', 'user',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('mangas', sa.Column('total_list', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('rating_9', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('total_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('rating_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('rating_7', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('rating_8', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('reading', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('completed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('rating_10', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('rating_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('rating_4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('mangas', sa.Column('favorite', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('on_hold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('dropped', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('rating_5', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('rating_3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('rating_6', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mangas', sa.Column('planned', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('mangas', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mangas', 'preview_picture_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('ratings')
    op.drop_table('lists')
    # ### end Alembic commands ###
