"""second test

Revision ID: b40373ba268f
Revises: e805b8d1d0e2
Create Date: 2025-08-07 23:42:59.214674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b40373ba268f'
down_revision: Union[str, Sequence[str], None] = 'e805b8d1d0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mangas', 'preview_picture_id',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('pages', sa.Column('page_id', sa.Integer(), nullable=False))
    op.alter_column('pages', 'comments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'comments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('pages', 'page_id')
    op.alter_column('mangas', 'preview_picture_id',
               existing_type=sa.Integer(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
