"""Add Mangas, Pages, Reviews, Users

Revision ID: b87f66b4bb63
Revises: 9b71faa11bcf
Create Date: 2025-08-07 19:49:48.741592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87f66b4bb63'
down_revision: Union[str, Sequence[str], None] = '9b71faa11bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mangas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preview_picture_id', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('chapter_size', sa.Integer(), nullable=False),
    sa.Column('volume_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=False),
    sa.Column('bookmarks', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('comments', sa.JSON(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Mangas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Mangas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('preview_picture_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artist', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chapter_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('volume_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Mangas_pkey'))
    )
    op.drop_table('reviews')
    op.drop_table('pages')
    op.drop_table('users')
    op.drop_table('mangas')
    # ### end Alembic commands ###
