"""mangas11

Revision ID: e5e1645f7b1e
Revises: c2198f8264e2
Create Date: 2025-08-24 23:00:37.547000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5e1645f7b1e'
down_revision: Union[str, Sequence[str], None] = 'c2198f8264e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mangas1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alternative_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('chapter_size', sa.Integer(), nullable=False),
    sa.Column('volume_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('time', sa.String(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('author', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('izdat', sa.String(), nullable=False),
    sa.Column('rating_10', sa.Integer(), nullable=False),
    sa.Column('rating_9', sa.Integer(), nullable=False),
    sa.Column('rating_8', sa.Integer(), nullable=False),
    sa.Column('rating_7', sa.Integer(), nullable=False),
    sa.Column('rating_6', sa.Integer(), nullable=False),
    sa.Column('rating_5', sa.Integer(), nullable=False),
    sa.Column('rating_4', sa.Integer(), nullable=False),
    sa.Column('rating_3', sa.Integer(), nullable=False),
    sa.Column('rating_2', sa.Integer(), nullable=False),
    sa.Column('rating_1', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mangas1')
    # ### end Alembic commands ###
