"""more and more

Revision ID: ef3156d69c04
Revises: c75898099e14
Create Date: 2025-08-18 13:58:59.072850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3156d69c04'
down_revision: Union[str, Sequence[str], None] = 'c75898099e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'manga_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mangas', 'preview_picture_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mangas', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mangas', 'total_list',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'reading',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'planned',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'completed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'favorite',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'on_hold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'dropped',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'total_rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_10',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_9',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_8',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_7',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_6',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_5',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_4',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_3',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('reviews_manga_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('reviews_manga_id_fkey'), 'reviews', 'mangas', ['manga_id'], ['id'])
    op.alter_column('mangas', 'rating_1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_3',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_4',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_5',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_6',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_7',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_8',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_9',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'rating_10',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'total_rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'dropped',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'on_hold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'favorite',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'completed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'planned',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'reading',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'total_list',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mangas', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mangas', 'preview_picture_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('comments', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'manga_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
