"""nullable

Revision ID: f448c9999fa5
Revises: b87f66b4bb63
Create Date: 2025-08-07 22:45:35.913093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f448c9999fa5'
down_revision: Union[str, Sequence[str], None] = 'b87f66b4bb63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mangas', 'preview_picture_id',
               existing_type=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mangas', 'preview_picture_id',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
